Start-Process python -ArgumentList "./valentao.py 1"
Start-Process python -ArgumentList "./valentao.py 2"
Start-Process python -ArgumentList "./valentao.py 3"
Start-Process python -ArgumentList "./valentao.py 4"
Start-Process python -ArgumentList "./valentao.py 5"
